### ISSUE TITLE
Add ID() to Entity

### ISSUE THREAD

**Issue by delaneyj** [zdandoh/ecs#3]

**Comment by zdandoh** [comment]
I had actually added this previously and then removed it because I felt that it broke the abstraction of the library more than needed. I added `entity.Is() and entity.Zero()` instead, is there a specific use case you're thinking of for this?

**Comment by delaneyj** [comment]
Debug, logging and serialization all need ways to know the ID

**Comment by zdandoh** [comment]
Sounds good, added.
