### ISSUE TITLE
Optimization match

### ISSUE THREAD

**Issue by delaneyj** [zdandoh/ecs#4]
Like #2 there is an opportunity to fast out of Select `match`

```go
case func(Entity, *comp.Position, *comp.Velocity, ) :
  for i := 0; i < currEntities; i++ {
     entity = entities[i>>entityPageBits][i%entityPageSize]
     match = match && entity.components[0] & 1 != 0
     match = match && entity.components[0] & 2 != 0
            
     if match {
                fun(entity, &storePosition[entity.id >> entityPageBits][entity.id % entityPageSize], &storeVelocity[entity.id >> entityPageBits][entity.id % entityPageSize], )
                
     }
}
```

If the first `match` is false then it could early out.  Not huge in this case but with you have more components its a way to early out.  The other option is to at pub/sub and have the `Select` have lists of entities to iterate knowing that don't have to match.

**Comment by zdandoh** [comment]
Nice, thanks for the suggestion. I've implemented this and it gave a small but noticeable improvement. I also moved the entities[i>>entityPageBits] pointer dereference out of the hot loop. Those two together made Select ~30% faster on my machine.

**Comment by zdandoh** [comment]
Looks like using a range for loop was also faster than a C style for loop, probably because it allows the compiler to elide the bounds check on the slice access. I've implemented that as well.
