### ISSUE TITLE
No codegen for unset of a component

### ISSUE THREAD

**Issue by delaneyj** [zdandoh/ecs#7]
:point_up: 

It seems like 
```
func (e Entity) UnsetPosition() {
	if !e.Alive() {
		return
	}

	entities[e.id>>entityPageBits][e.id%entityPageSize].components[0] &= ^uint64(1)
}
```

Would be basically the right format and fast since you are using "dumb" slices as the backing store

**Comment by zdandoh** [comment]
Is this different from `RemoveX`?
https://github.com/zdandoh/ecs/blob/master/codegen/ecs/component.go.templ#L34

**Comment by delaneyj** [comment]
Lol, the codegen is tiny and I missed it... though the setting to zero isn't needed since when you add you are providing a new one

**Comment by zdandoh** [comment]
Yep, seems ok to remove. Done

**Comment by zdandoh** [comment]
Had to re-add the zeroing, if you don't zero you don't clear out any pointers that might have been heap allocated by the user and they can't be GC'd.
